finish generic docker deployment

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -1,39 +1,39 @@
 FROM ghcr.io/cirruslabs/flutter:stable as builder
 
-# E.g. app or designer
-ARG FLUTTER_APP_FOLDER
-
-#RUN flutter config --enable-web
-
 ENV PATH ${PATH}:/root/.pub-cache/bin/
+
+# Create workdir
+WORKDIR /src/
 
 # Install melos
 RUN dart pub global activate melos
 
-# SETUP STUDYU
-WORKDIR /src/
-
-COPY melos.yaml melos.yaml
-
-COPY pubspec.yaml pubspec.yaml
-COPY pubspec.lock pubspec.lock
-
-COPY core/pubspec.yaml core/pubspec.yaml
-COPY core/pubspec.lock core/pubspec.lock
-
-COPY flutter_common/pubspec.yaml flutter_common/pubspec.yaml
-COPY flutter_common/pubspec.lock flutter_common/pubspec.lock
-
-COPY $FLUTTER_APP_FOLDER/pubspec.yaml $FLUTTER_APP_FOLDER/pubspec.yaml
-COPY $FLUTTER_APP_FOLDER/pubspec.lock $FLUTTER_APP_FOLDER/pubspec.lock
-
-RUN flutter pub get
-RUN melos cleandocker
-RUN melos bootstrap
-
+# Copy repository files
 COPY ./ ./
 
-# Env variable from docker-compose-*.yaml is used here if set
+# Clean repository without failing
+RUN melos clean || true
+
+# Setup workspace
+RUN flutter pub get
+RUN melos bootstrap
+
 ARG STUDYU_ENV
-RUN if [ -n "$STUDYU_ENV" ] ; then melos run build:web:$FLUTTER_APP_FOLDER:$STUDYU_ENV ; else melos run build:web:app ; fi
-RUN if [ -n "$STUDYU_ENV" ] ; then melos run build:web:$FLUTTER_APP_FOLDER:$STUDYU_ENV ; else melos run build:web:$FLUTTER_APP_FOLDER ; fi
+
+# Build apps
+RUN if [ -n "$STUDYU_ENV" ] ; then melos run build:web:app:$STUDYU_ENV ; else melos run build:web:app ; fi
+RUN if [ -n "$STUDYU_ENV" ] ; then melos run build:web:designer_v2:$STUDYU_ENV ; else melos run build:web:designer_v2 ; fi
+
+# Configure webserver
+FROM nginx:stable-alpine
+
+# Copy web builds from the builder image to the webserver
+COPY --from=builder /src/app/build/web /usr/share/nginx/html/app
+COPY --from=builder /src/designer_v2/build/web /usr/share/nginx/html/designer_v2
+
+# Loads all env vars starting with "STUDYU" into the .env file for flutter apps
+#RUN mkdir /usr/share/nginx/html/app/assets/envs
+#RUN mkdir /usr/share/nginx/html/designer_v2/assets/envs
+
+#CMD ["sh", "-c", "printenv | grep STUDYU_ > /usr/share/nginx/html/app/assets/envs/.env && nginx -g 'daemon off;'"]
+#CMD ["sh", "-c", "printenv | grep STUDYU_ > /usr/share/nginx/html/designer_v2/assets/envs/.env && nginx -g 'daemon off;'"]
